# Generated by Django 5.2.1 on 2025-11-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_card', models.IntegerField(max_length=16)),
                ('cardholder_name', models.CharField(max_length=50)),
                ('expiration_date', models.CharField(max_length=5)),
                ('cvv', models.IntegerField(max_length=3)),
            ],
        ),
    ]
