# Generated by Django 5.2.1 on 2025-11-01 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(help_text='3 or 4 digits.', max_length=4, validators=[django.core.validators.RegexValidator(message='CVV must contain 3 or 4 digits.', regex='^\\d{3,4}$')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='number_card',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='The card number must contain between 13 and 16 digits.', regex='^\\d{13,16}$')]),
        ),
    ]
