# Generated by Django 5.2.1 on 2025-11-01 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_api', '0002_alter_card_cvv_alter_card_number_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='CVV must contain 3 or 4 digits.', regex='^\\d{3}$')]),
        ),
    ]
