# Generated by Django 5.2.1 on 2025-11-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_api', '0003_alter_card_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardholder_name',
            field=models.CharField(max_length=20),
        ),
    ]
